<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="R_Yamini" failures="1" tests="2" name="runner.TestRunner_Plumbing_Service" time="52.769" errors="0" timestamp="2025-09-10T19:41:54 IST" skipped="0">
  <testcase classname="runner.TestRunner_Plumbing_Service" name="runScenario" time="30.770">
    <failure message="❌ Login failed! expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: ❌ Login failed! expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at stepdefinitions.Plumbing_Service_StepDef.the_user_logs_in_with_a_valid_mobile_number_and_otp(Plumbing_Service_StepDef.java:32)
at ✽.the user logs in with a valid mobile number and OTP(file:///C:/Users/yamin/git/NOBROKER_TEST_APPLICATION/NOBROKER_TEST_APPLICATION/src/test/resources/features/plumbingservice.feature:11)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="runner.TestRunner_Plumbing_Service" name="runScenario" time="21.999"/>
</testsuite> <!-- runner.TestRunner_Plumbing_Service -->
