<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="R_Yamini" failures="6" tests="20" name="runner.TestRunner_Login" time="521.925" errors="0" timestamp="2025-09-11T08:25:47 IST" skipped="0">
  <testcase classname="runner.TestRunner_Login" name="runScenario" time="25.968"/>
  <testcase classname="runner.TestRunner_Login" name="runScenario" time="35.699">
    <failure message="❌ Login failed! expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: ❌ Login failed! expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at stepdefinitions.Salesagreement_Stepdef.the_user_logs_in_with_a_valid_mobile_number_and_otp_for_sales(Salesagreement_Stepdef.java:28)
at ✽.the user logs in with a valid mobile number and OTP for sales(file:///C:/Users/yamin/git/NOBROKER_TEST_APPLICATION/NOBROKER_TEST_APPLICATION/src/test/resources/features/salesagreement.feature:10)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="runner.TestRunner_Login" name="runScenario" time="20.605"/>
  <testcase classname="runner.TestRunner_Login" name="runScenario" time="23.560"/>
  <testcase classname="runner.TestRunner_Login" name="runScenario" time="20.808"/>
  <testcase classname="runner.TestRunner_Login" name="runScenario" time="49.741"/>
  <testcase classname="runner.TestRunner_Login" name="runScenario" time="20.974"/>
  <testcase classname="runner.TestRunner_Login" name="runScenario" time="18.033"/>
  <testcase classname="runner.TestRunner_Login" name="runScenario" time="36.140">
    <failure message="❌ Login failed! expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: ❌ Login failed! expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at stepdefinitions.Home_Cleaning_Stepdef.the_user_logs_in_successfully_for_home(Home_Cleaning_Stepdef.java:40)
at ✽.the user logs in successfully for home(file:///C:/Users/yamin/git/NOBROKER_TEST_APPLICATION/NOBROKER_TEST_APPLICATION/src/test/resources/features/homecleaning.feature:4)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="runner.TestRunner_Login" name="runScenario" time="38.484">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at stepdefinitions.Landmark_Stepdef.an_error_message_should_be_displayed(Landmark_Stepdef.java:46)
at ✽.an error message should be displayed(file:///C:/Users/yamin/git/NOBROKER_TEST_APPLICATION/NOBROKER_TEST_APPLICATION/src/test/resources/features/landmark.feature:19)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="runner.TestRunner_Login" name="runScenario" time="35.299"/>
  <testcase classname="runner.TestRunner_Login" name="runScenario" time="14.430"/>
  <testcase classname="runner.TestRunner_Login" name="runScenario" time="33.559">
    <failure message="Login was not successful! expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Login was not successful! expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at stepdefinitions.Login_StepDef.the_user_should_be_logged_in_successfully(Login_StepDef.java:81)
at ✽.the user should be logged in successfully(file:///C:/Users/yamin/git/NOBROKER_TEST_APPLICATION/NOBROKER_TEST_APPLICATION/src/test/resources/features/login.feature:38)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="runner.TestRunner_Login" name="runScenario" time="7.229"/>
  <testcase classname="runner.TestRunner_Login" name="runScenario" time="29.674"/>
  <testcase classname="runner.TestRunner_Login" name="runScenario" time="21.738"/>
  <testcase classname="runner.TestRunner_Login" name="runScenario" time="7.080"/>
  <testcase classname="runner.TestRunner_Login" name="runScenario" time="32.193">
    <failure message="❌ Login failed! expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: ❌ Login failed! expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at stepdefinitions.Plumbing_Service_StepDef.the_user_logs_in_with_a_valid_mobile_number_and_otp(Plumbing_Service_StepDef.java:32)
at ✽.the user logs in with a valid mobile number and OTP(file:///C:/Users/yamin/git/NOBROKER_TEST_APPLICATION/NOBROKER_TEST_APPLICATION/src/test/resources/features/plumbingservice.feature:11)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="runner.TestRunner_Login" name="runScenario" time="20.006"/>
  <testcase classname="runner.TestRunner_Login" name="runScenario" time="30.705">
    <failure message="Login failed! expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Login failed! expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at stepdefinitions.Subscription_Stepdef.the_user_logs_in_with_a_valid_mobile_number_and_otp(Subscription_Stepdef.java:27)
at ✽.the user is logged in(file:///C:/Users/yamin/git/NOBROKER_TEST_APPLICATION/NOBROKER_TEST_APPLICATION/src/test/resources/features/subscription.feature:4)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- runner.TestRunner_Login -->
